name: Deploy to S3 Bucket

on:
  push:
    branches:
    - main
    # paths:
    #   - '**/*.html'  # solo hace deploy cuandi los archivos HTML son modificados 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Step 3: Install AWS CLI
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    # Step 4: Sync HTML files to the S3 bucket
    - name: Sync HTML files to S3
      run: |
        aws s3 sync ./my_images/node_app/public s3://practica-s3-con-politica-de-retencion --delete  
