name: Build_chatbot

on:
  push:
    branches:
      - main
    paths:
      - 'g2-cdt-m3-c8-node_dia_31/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ECR_URL: 248189943700.dkr.ecr.eu-west-2.amazonaws.com/repositorio-grupo-dos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          cd g2-cdt-m3-c8-node_dia_31
          docker build --no-cache -t chat-bot .
      
      - name: Tag Docker image
        run: |
          docker tag chat-bot:latest ${{ env.ECR_URL }}:chat-bot

      - name: Push image to ECR
        run: |
          docker push ${{ env.ECR_URL }}:chat-bot
          
