name: Upload to S3 Bucket html

on:
  push:
    branches:
    - main
    paths:
       - 'g2-cdt-m4-c1-node_app/public/**'    # solo hace deploy cuando los archivos HTML son modificados 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


    # Step 4: Sync HTML files to the S3 bucket
    - name: Sync HTML files to S3
      run: |
        aws s3 sync ./g2-cdt-m4-c1-node_app/public s3://practica-s3-con-politica-de-retencion --delete  
